### ISSUE TITLE
rbg_to_hex.cc fix bugs

### ISSUE THREAD

**Issue by amandabarth** [danieleror/4-11-practice#12]
Reproduce the bug: use the values given in the fil eand the first and last two digits of the hex code are switched. It gives a hex code, however it does not give the expected hex code. The order of the rgb values are incorrect in line 13. Possible solution is to swap the r and g values in the string stream. Priority Low but an easy fix and can be reproduced and impacts the validity of the hex code, given that r and g do not have the same value.

**Comment by Elias-Malloy** [comment]
done
